# 数据源集合
dataSources:
  # 逻辑数据源名称
  ds_0:
    # 数据源类型
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    # 数据库驱动
    driverClassName: com.mysql.cj.jdbc.Driver
    # 数据库连接
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/count?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    # ShardingSphere 规则配置，包含：数据分片、数据加密、读写分离等

rules:
  # 需要数据分片的表集合
  - !SHARDING
    tables:
      # 逻辑表名
      count:
        # 真实存在数据库的物理表集合
        actualDataNodes: ds_0.count_${0..31}
        # 分表策略
        tableStrategy:
          # 单分片键分表
          complex:
            # 自定义分片字段
            shardingColumns: count_key,obj_id
            # 自定义分片算法名称，对应 {rules[0].shardingAlgorithms.user_table_hash_mod}
            shardingAlgorithmName: count_complex_mod
    shardingAlgorithms:
      count_complex_mod:
        type: CLASS_BASED
        props:
          algorithmClassName: cn.dbj.utils.CountKeyShardingAlgorithm
          sharding-count: 32
          strategy: complex


props:
  # 是否打印逻辑SQL和真实SQL，开发测试环境建议开放，生产环境建议关闭
  sql-show: true

